# Generated by Django 3.2.4 on 2021-07-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemons',
            new_name='Pokemons_1',
        ),
    ]
