# Generated by Django 3.2.4 on 2021-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('height', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('category', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('abilities', models.CharField(max_length=150)),
            ],
        ),
    ]
