# Generated by Django 3.2.4 on 2021-07-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemons',
            old_name='category',
            new_name='types',
        ),
        migrations.RemoveField(
            model_name='pokemons',
            name='gender',
        ),
    ]
