# Generated by Django 3.2.4 on 2021-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_alter_pokemons_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='picture_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
