# Generated by Django 3.2.4 on 2021-07-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_pokemons_picture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='picture_name',
        ),
    ]
