# Generated by Django 3.2.4 on 2021-07-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0005_remove_pokemons_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='picture',
            field=models.FileField(default=None, upload_to='../templates/picture'),
            preserve_default=False,
        ),
    ]
