# Generated by Django 3.2.4 on 2021-07-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0006_pokemons_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='picture',
        ),
    ]
