# Generated by Django 3.2.4 on 2021-07-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0007_remove_pokemons_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='picture_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
