# Generated by Django 3.2.4 on 2021-07-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0008_pokemons_picture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
