# Generated by Django 3.2.4 on 2021-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0009_alter_pokemons_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='picture_name',
        ),
        migrations.AddField(
            model_name='pokemons',
            name='picture_status',
            field=models.BooleanField(default=False),
        ),
    ]
